### ISSUE TITLE
Clang linker on Windows

### ISSUE THREAD

**Issue by egladil** [maven-nar/nar-maven-plugin#252]
Using clang as linker on Windows causes nar to try to execute gcc instead.

I believe the cause is at the end of com.github.maven_nar.cpptasks.gcc.GccLinker, in method getLinker(...). Looks like it will always use dllLinker on windows, which causes the executable name to be gcc instead of clang.

**Comment by ctrueden** [comment]
@egladil Would you care to file a PR to address this?

**Comment by egladil** [comment]
Unfortunately I don't have a fix for it. The information above was what I could discern from a quick look around. Then I worked around it by renaming my linker executable on disk.

**Comment by bchiodo** [comment]
I don't have a Windows system to quickly test this on, but this should be fixed by a03d32760ca34a833a4e040a60ec6e09bdf4e07b. If it isn't, reopen.

**Comment by egladil** [comment]
I don't have the project I needed this for set up any longer so I can't easily test it, but from the looking at the commit I think this will still fail if you are trying to build a shared library, jni module (which was my use case), or a plugin module
